### ISSUE TITLE
Testing: Zotero Citations module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ZoteroCitations#1]
This module adds [Zotero](https://www.zotero.org/) citation and bibliography features to rich-text editors in the Omeka S administrative interface. You will need access to at least one Zotero library to test this module. I can provide you access if you don't already have it.

First, install the module and edit your Omeka S user account. Under "User settings" you should see seven fields beginning with "Zotero Citation". These are all optional, but you should at least enter a valid "Library ID" (again, I can provide you with one). Save the form.

Next, go to anywhere in the administrative interface where there's a rich-text editor. For example, add a new item and add "HTML" media. You should see a WYSIWYG box with toolbars. On that toolbar you should see a red "Z"  for Zotero. Click on that icon and a dialog should open with three tabs: Add citation, Add bibliography, and Settings.

The "Add citation" tab is where you search for Zotero items and add citations to the editor where your cursor is. Try this out a number of times. Perform many searches; paginate through the results; select many citations; and add them to the editor.

The "Add bibliography" tab is where you add a bibliography to the editor where your cursor is. After you have a few citations in the editor, check the box, press OK, and you should see a formatted bibliography in the editor.

The "Settings" tab is where you make temporary changes to the default settings. Try out every setting and see if it affects subsequent use of the Zotero tool. Note that any change you make to the user settings should be reflected in this "Settings" tab. Make sure that's the case.

**Comment by katknow** [comment]
When I try to install the module, I get this error:


Omeka S encountered an error

ParseError
syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN)

Details:

ParseError: syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN) in /var/www/html/katknow/OmekaSTesting/modules/ZoteroCitations/Module.php:277
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-loader/src/ModuleAutoloader.php(206): Laminas\Loader\ModuleAutoloader->loadModuleFromDir('/var/www/html/k...', 'ZoteroCitations...')
#1 [internal function]: Laminas\Loader\ModuleAutoloader->autoload('ZoteroCitations...')
#2 /var/www/html/katknow/OmekaSTesting/application/src/Module/Manager.php(368): spl_autoload_call('ZoteroCitations...')
#3 /var/www/html/katknow/OmekaSTesting/application/src/Module/Manager.php(239): Omeka\Module\Manager->getModuleObject(Object(Omeka\Module\Module))
#4 /var/www/html/katknow/OmekaSTesting/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module))
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ModuleController->installAction()
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(105): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#10 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#14 {main}

**Comment by katknow** [comment]
This seems to work pretty well! The one question I have is should I be able to add more than one citation at a time? Or should I have to reopen the Zotero tool every time? I wasn't sure based on the wording--I can only check on resource at a time.

**Comment by jimsafley** [comment]
Glad things are working well. I imagine users will only add one citation at a time. Given that a citation will be added at the current location of the cursor, I can't think of a reason why a user would want more than one citation at the cursor.

**Comment by sharonmleon** [comment]
Well, depends on the kind of work you're doing. I often cite several sources for a piece of information.

**Comment by jimsafley** [comment]
Then you would have to add each citation one at a time.

**Comment by sharonmleon** [comment]
That makes sense. I was just trying to think about how that works with the other connectors. You get the site and then the opportunity to add the pages and then I can't remember what happens. Maybe it closes and you have to start over for the next one.

**Comment by sharonmleon** [comment]
@jimsafley I'm working on the documentation for this module, and when I change my library ID within the Zotero popup at the editing interface, it's not overwriting the selection made under my user settings. I made a mistake there and went to fix it in the course of using the module. No luck.

**Comment by sharonmleon** [comment]
Also, when performing a search, if you hit enter, the dialog box disappears, rather than triggering the "Search library" function.

As for the setting issue, I think the problem is that it's not clear that the settings need to be adjusted and the search performed before clicking okay. It seems like you should have to click okay to set the adjustments, and then you can return to citations, but you don't. You should just go back to the Add citation workflow. Maybe there is some interface work to be done here?

**Comment by jimsafley** [comment]
There's only so much we can do to optimize the UI and workflow in the CKEditor dialog. Its API is not very flexible—the Zotero dialog is already pushing its limits quite a bit. I'll look into it, but we may have to settle with what we have and depend on documentation to teach proper workflow.

**Comment by sharonmleon** [comment]
Okay. I figured it was worth asking. I hit that return button about four times before I resisted the instinct....

**Comment by jimsafley** [comment]
I made some changes that should make the workflow less irritating. It's a simple matter of disabling the OK button when the user shouldn't use it.

**Comment by sharonmleon** [comment]
Thanks. That definitely helps.
